- README.md
- buf.gen.yaml
- buf.yaml
- proto/validator.proto
- src/gen.rs
- src/gen/mod.rs
If other consumers want to use this, generating code is as simple as `buf generate https://github.com/LayerTwo-Labs/bip300301_enforcer.git`
> proto: move files to this repository

- README.md
Is this an extra "cargo run --" ?
> Update README.md cargo run example

- src/wallet.rs
Sidechain wallet is already implemented in Thunder.
> Delete sidechain wallet implementation

- build.rs
- proto/mainchain/v1/mainchain.proto
- src/gen.rs
Add mainchain.proto file from `cusf_sidechain_proto` repository.
> Add mainchain.proto definition

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/server.rs
- src/wallet.rs
Some notes here: 
1. The gRPC endpoints are all unimplemented. I had hoped to get to actually implementing at least one, but setting up the scaffold was more work than I anticipated. 
2. I had to fight with the borrow checker **a lot**. Not because I do hard things here, but because I don't really know Rust. I might be doing things in a strange way! 
3. ~There's a complaint from Clippy that seems significant. No idea how to fix it... https://github.com/LayerTwo-Labs/bip300301_enforcer/pull/29/files#diff-4db9c4cca2ff80c2ad80cbf7111959e148b31ee24cb354f8620c417047fe7b46R903-R908~
> multi: add empty wallet gRPC service scaffold

- src/wallet.rs
* Enforcer shouldn't expect sidechains to implement particular RPCs
Closes #17
> Remove sidechain clients from wallet

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/server.rs
- src/wallet.rs
I tried addressing your comments @Ash-L2L .
> wallet gRPC scaffold - this time against the correct branch

- Cargo.lock
- Cargo.toml
- src/messages.rs
- src/proto.rs
- src/server.rs
- src/validator/dbs/mod.rs
- src/validator/mod.rs
- src/validator/task.rs
- src/zmq.rs
Closes #32 . Adds @nchashch as co-author, as this is solely cribbed code.
> multi: pull bip300301_messages into this repo

- src/messages.rs
- src/server.rs
- src/wallet.rs
> Implement generate_blocks RPC

- src/messages.rs
- src/validator/task.rs
> messages: adjust M8 BMM request parsing

- src/cli.rs
- src/main.rs
- src/server.rs
- src/wallet/error.rs
- src/wallet/mod.rs
1. Give a clear error message that we cannot generate blocks on a non-regtest network
2. Add better error messages to the mining process
> multi: mining improvements

- src/messages.rs
- src/proto.rs
- src/server.rs
- src/types.rs
- src/validator/task.rs
- src/wallet/mod.rs
Should be updated after https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/21 is merged
> wallet: implement auto-ACKing of SC proposals

- src/messages.rs
- src/server.rs
- src/wallet/mod.rs
> Fix BMM ack issues

- Cargo.lock
- Cargo.toml
- src/validator/mod.rs
- src/validator/task/error.rs
- src/validator/task/mod.rs
see https://github.com/LayerTwo-Labs/bip300301_enforcer/pull/54
> Distinguish between fatal and nonfatal errors explicitly

- README.md
- src/main.rs
- src/wallet/mod.rs
> docs: add note on buf curl to README

- src/proto.rs
- src/server.rs
If a source error is present on a `proto::Error`, it is added to the
returned error message. Furthermore, we make sure to also return a
`invalid_argument` code in the tonic statuses
> server: add source error to invalid_field_value

- .github/workflows/check_lint_build_release.yaml
- Cargo.lock
- Cargo.toml
- README.md
- integration_tests/integration_test.rs
- integration_tests/main.rs
- src/lib.rs
- src/main.rs
- src/messages.rs
- src/types.rs
- src/validator/dbs/block_hashes.rs
- src/validator/dbs/util.rs
- src/validator/mod.rs
- src/validator/task/mod.rs
- src/zmq.rs
> Integration test

- src/server.rs
- src/validator/mod.rs
- src/wallet/mod.rs
> Improve error messages during initial sync

- src/server.rs
- src/wallet/mod.rs
> wallet: validate non-empty destinations, above dust limit

- integration_tests/integration_test.rs
- integration_tests/util.rs
- src/bins.rs
- src/cli.rs
- src/lib.rs
- src/server.rs
- src/validator/task/error.rs
- src/validator/task/mod.rs
- src/wallet/mine.rs
- src/wallet/mod.rs
Supersedes #106. I had issues with rebasing, so I ended up saying "screw this" and just reimplement the same thing on master by copying over code without the git history.
> multi: parameterize more signet mining components

- src/main.rs
- src/wallet/mod.rs
* A broadcast channel is the wrong kind here, since there is only one consumer. Changed to use oneshot channels
* Removed the shutdown function on the wallet, send shutdown notification on drop instead
> Fixups for #126

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
This makes it a lot easier for users to debug what's going on, as well as provide logs for bug reports.
> main: write logs to file in addition to stdout

- .github/workflows/check_lint_build_release.yaml
replaces version number with latest
> disable version number appending to binary name

- Cargo.lock
- Cargo.toml
- app/main.rs
- lib/Cargo.toml
- lib/server.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
> Fix wallet sync issues (#147)

- app/main.rs
- lib/cli.rs
JSON logs give more contextual information!
> app: fully support JSON logs

- lib/server.rs
- lib/wallet/mod.rs
> wallet: implement ListUnspentOutputs

- lib/server.rs
- lib/wallet/mod.rs
This came up as a need for me when working on #169. I was moving wallets around, and needed to verify that I was able to import/sync correctly
Matching proto PR: https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/35
> wallet: implement GetInfo endpoint

- .github/workflows/check_lint_build_release.yaml
- README.md
- integration_tests/main.rs
- integration_tests/setup.rs
- integration_tests/util.rs
- lib/wallet/mod.rs
> multi: replace romanz/electrs with mempool/electrs

- Cargo.lock
- Cargo.toml
- lib/wallet/mod.rs
> deps: update cusf-enforcer-mempool

- lib/validator/cusf_enforcer.rs
- lib/validator/task/mod.rs
This seemingly minor change fixes an observed bug on signet:
Sidechain's requests for headers are hitting the Enforcer only 2550μs after broadcasting an event.
However, committing the db txs after broadcasting an event is taking slightly longer (unknown, but less than 6970μs)
This causes the Enforcer to respond that a block header is missing.
Fixed by broadcasting events only after committing state changes
> Ensure that events are broadcast only after committing db txs

- Cargo.lock
- lib/proto.rs
- lib/server.rs
- lib/types.rs
- lib/validator/cusf_enforcer.rs
- lib/validator/mod.rs
- lib/validator/task/error.rs
- lib/validator/task/mod.rs
- Add HeaderSyncProgress and SubscribeHeaderSync proto definitions
- Implement header sync streaming in validator
- Add subscribe_header_sync RPC endpoint with progress tracking
- Update submodule with proto changes
> Update to latest proto (header sync progress stream)

- lib/server.rs
Depends on https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/45
> server: include addresses when listing wallet UTXOs

- app/main.rs
- lib/validator/main_rest_client.rs
Closes #209.
Also make sure to give clearer error message if we're not able to reach Bitcoin Core at all.
> main: verify that Bitcoin Core REST server is enabled at startup

- app/main.rs
The error will look something like this for the user. The red text links to the README of this repo.
> main: ensure we're not on standard signet

- app/main.rs
1. Tune access log down to trace level
2. Give the error handler a more human-friendly output
> main: adjust gRPC server access logs

- Cargo.lock
- Cargo.toml
- app/Cargo.toml
- app/main.rs
- integration_tests/Cargo.toml
- integration_tests/mine.rs
- integration_tests/util.rs
- lib/Cargo.toml
- lib/cli.rs
- lib/rpc_client.rs
- lib/validator/mod.rs
- lib/validator/task/error.rs
- lib/validator/task/mod.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mine.rs
- lib/wallet/mod.rs
One less configuration option the user has to deal with!
> multi: fetch ZMQ address from Bitcoin Core if not provided

- README.md
- app/Cargo.toml
- app/main.rs
- lib/Cargo.toml
- scripts/analyze_sync_logs.py
- scripts/trace_enforcer_macos.sh
Adjust logs, a new tracing script, add a note to the README.
> multi: more analysis stuff
