- src/bip300.rs
- src/cli.rs
- src/main.rs
1. Adds support for username + password when creating the Core RPC client
2. Removes the data dir parameter, and instead adds a parameter that takes in the cookie path directly. This removes the hardcoded 'regtest' network, as a byproduct.
> config: add RPC user+password, rework cookie auth

- README.md
- proto/validator/v1/validator.proto
- src/server.rs
1. Clarify what the `GetCtip` endpoint does through a comment in the proto file
2. Proper error handling in `GetCtip`: 
1. Return an error if the sidechain is not found
2. Make the sidechain number request field optional. This is to differentiate _not_ passing a number from _passing 0_. The former is invalid, and we indicate this with a proper error message
3. Update the README with more context for devving
> server: comments, error response for get_ctip, input validation

- .github/workflows/check_lint_build_release.yaml
- .gitmodules
- Cargo.lock
- Cargo.toml
- build.rs
- src/gen.rs
- src/main.rs
- src/server.rs
- src/validator.rs
- src/wallet.rs
1. Rename `Bip300` to `Validator`, to make it clearer what this does.
2. Copy over the wallet implementation from the `bip300301_wallet` repo.
3. Replaced usage of the `bs58` library with `rust-bitcoin`, since this is already in the dependency tree through BDK
4. Same goes for the `bip39` library
5. Note that we're using an outdated version of `cusf_sidechain_proto`. This is to minimize the changes done here.
6. Note that none of this is tested, nor exposed anywhere. This is also to minimize the changes needed in copying over the wallet.
> multi: pull bip300301_wallet into enforcer

- .prettierignore
- src/cli.rs
- src/main.rs
- src/validator.rs
- src/wallet.rs
1. Refactor the way we start tasks. Exit the entire application if any of the tasks fail
2. Verify we're able to connect to the mainchain on startup, with a short-timeout JSON-RPC request. 
3. Add a CLI option `--enable-wallet` for "starting" the wallet. Right now we just instantiate it, and verify that we're able to wire things correctly together. Note: you'll most likely **not** be able to do this, as the wallet has hard coded paths to an Electrum server that needs to be running. If you see "failed to create wallet:   × Connection refused (os error 61)", that means its "working".
> multi: verify connection to mainchain, "start" wallet

- .gitignore
- src/wallet.rs
Fixes:
```
Error:   × failed to create wallet:   × transport error
│   ├─▶ tcp connect error: Connection refused (os error 111)
│   ├─▶ tcp connect error: Connection refused (os error 111)
│   ╰─▶ Connection refused (os error 111)
│
```
on startup when `--enable-wallet` is passed.
Also add wallet-db to `.gitignore`.
> Comment out attempt to connect to sidechains

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/jsonrpc.rs
- src/main.rs
- src/validator.rs
- src/wallet.rs
Adds configuration values for electrum, data dir, and wallet network.
Also ensures that we use the same configuration for connecting to the mainchain using JSON-RPC both inside the wallet and the validator, by extracting this to a new `jsonrpc.rs` file. 
Configures logging, with Clippy lints and README information. 
Sets up periodic syncs of the wallet from the task list ran in main.
> multi: add more configuration values + proper logging

- .github/workflows/check_lint_build_release.yaml
- src/main.rs
- src/messages.rs
- src/validator/task.rs
This partially implements the solution sketched out here: https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/5#discussion_r1793646099
After https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/5 is landed, the idea is to add an endpoint that exposes this functionality. 
~One issue: this is not behaving precisely as expected... I'm unsure if this is due do a bug in one of the upstream bip300 libraries, or due to me misunderstanding things. See https://github.com/LayerTwo-Labs/bip300301_enforcer/pull/28/files#diff-a8412c4f5f378292029d100f76c5941c636af5cc429f504e82a636f1946fc3d2R1026-R1030~
The above was a misunderstanding on my part! Cleared up after talking with @Ash-L2L in private.
> validator: add function + test for creating sidechain proposal

- README.md
- src/convert.rs
- src/main.rs
- src/messages.rs
- src/server.rs
- src/validator/mod.rs
- src/wallet/error.rs
- src/wallet/mod.rs
~This is currently not working.~
~I'm not sure how to add the previous Ctip to the OP_DRIVECHAIN TX. I'm using `add_foreign_utxo`, but don't know how to obtain the `psbt_input` and `satisfaction_weight` values to pass in as parameters to that method. ~
~I'm able to create a transaction, but having some issues with both broadcasting as well as adding the previous Ctip for the sidechain.~
Update: was able to broadcast the TX, with help from @CryptAxe . Was missing the `acceptnonstdtxn` parameter for my local Core node. Updated the README.
Example of a created transaction: 
```
01000000000101516a86d7e375cd3295288eaed9b691734e5a218e7e02c99fff6e8196977b84b40100000000feffffff030000000000000000086a06666f6f626172d20400000000000004b4010051a114f505000000001600144d5107fd06c1935a71774c597e75f559def104 …
```
> multi: implement create_deposit_transaction

- .github/workflows/check_lint_build_release.yaml
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/convert.rs
- src/main.rs
- src/server.rs
- src/wallet/error.rs
- src/wallet/mod.rs
Bump to BDK v1 (beta5). The idea was to bump to this so I could set up Bitcoin Core RPC as the chain backend on regtest, but this proved to be too complex to be worth it. The bump is nice, anyways!
Some other quality of life improvements: 
1. Verify the Electrum server is on the same network as we are on startup, giving a clear error message if this is not the case
2. Set dynamic default Electrum connection details, based on the network we're on. 
3. Add the current network to the data directory path. Without this, we get an error message when switching between regtest and signet. 
4. Update the README to include a section on the Electrum server part. 
I'm having some issues with the `significant_drop_tightening` Clippy lint. IMO we should drop it. It's a massive PITA with unclear …
> multi: bump to BDK v1, electrum server adjustments

- src/server.rs
- src/validator/task/mod.rs
- src/wallet/mod.rs
The two tables `deposits` and `mempool` were used to fetch pending
sidechain deposits that should be included in newly generated blocks.
These tables were never written to, and therefore sidechain deposits
didn't get included either.
Instead of keeping these tables in sync with the raw mempool, we fetch
this with RPC inside the block construction process.
With this branch I was able to make a sidechain deposit on my local regtest. Note that I was **not** able to do a second sidechain deposit. This is because the second sidechain deposit requires us to spend the previous ctip, and the wallet fails to sign this. This is not new behavior, but rather a bug (I believe) in how we add the foreign UTXO when constructing the deposit transaction. I think this would be best handled in a different …
> wallet: remove mempool + deposits tables, fetch raw mempool in block construction

- Cargo.lock
- src/main.rs
- src/messages.rs
- src/proto.rs
- src/server.rs
- src/types.rs
- src/validator/dbs/block_hashes.rs
- src/validator/dbs/mod.rs
- src/validator/mod.rs
- src/validator/task/error.rs
- src/validator/task/mod.rs
- src/wallet/mod.rs
* Deletes failed and successful withdrawal bundles from the wallet
* Reject blocks with duplicate M2 for a sidechain slot
* Reject blocks with duplicate M4
* Handle one-byte M4 case correctly
* Accept M1 proposals that have the same description, but different sidechain slots
* Do not re-include failed M3 messages
* Wallet: create M6 txs when building blocks
* Fix encoding for blinded M6
* Exit on validator error, ctrl-c handler
Fixes #92, #31
> Include M3/M4 messages in mined blocks, handle Deposits and Withdrawals

- Cargo.lock
- Cargo.toml
- integration_tests/signet.rs
- integration_tests/util.rs
- src/cli.rs
- src/main.rs
- src/server.rs
- src/wallet/error.rs
- src/wallet/mnemonic.rs
- src/wallet/mod.rs
The wallet is now no longer initialized with a hard coded BIP39 seed. In this PR we add support for both plaintext + encrypted mnemonics. They can either be passed in through the new `CreateWallet` endpoint, or generated automatically. 
For testing/dev purposes we also add a new `--wallet-auto-init` flag that generates a brand new, plaintext mnemonic if it doesn't already exist. 
TODO:
> multi: implement wallet initialization from BIP39 seed

- Cargo.lock
- Cargo.toml
- src/main.rs
Latest cusf-enforcer-mempool Fixes #117
> Logs: disable ANSI escape codes if writer is not a terminal, update cusf-enforcer-mempool

- .github/workflows/check_lint_build_release.yaml
The actual executable file itself should have the `.exe` suffix, but not the folder. 
Closes #95
> ci: avoid creating artifact dir names with .exe in name

- Cargo.lock
- Cargo.toml
- src/server.rs
- src/types.rs
- src/validator/dbs/mod.rs
- src/validator/mod.rs
- src/validator/task/error.rs
- src/validator/task/mod.rs
- src/wallet/mod.rs
This is a breaking change to the validator DB.
Upgrading the signet miner server will require:
* stopping the mining script
* saving the wallet db
* syncing a new enforcer (v0.2.0) with a different data dir, etc, in order to get a new validator db
* shutting down the old enforcer (v0.1.x)
* copying over the wallet db
> update proto, track ctip seq numbers, bump minor version

- Cargo.lock
- app/Cargo.toml
- app/main.rs
Adds a new ID to all requests/responses. The ID is propagated to logs, under the `request_id` field. The ID can be specified in the request, in the `x-request-id` header. If none is provided, a random UUID is used. The request ID is sent back in the response, in the same header.
> app: add request IDs to req/res/traces

- app/main.rs
- lib/cli.rs
- lib/validator/task/mod.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
- lib/wallet/util.rs
This is intended to be used for importing a wallet from an existing
seed.
> wallet: add full scan functionality

- Cargo.lock
- app/main.rs
- lib/Cargo.toml
- lib/server.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mine.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
- lib/wallet/thread_safe_connection.rs
Currently struggling with the type check 😅 
Need to be able to run async functions within `with_mut` of the wallet `RwLockWriteGuardSome`. Is that possible?
> multi: asyncify, use rusqlite-based persistence

- Cargo.lock
- app/main.rs
- lib/Cargo.toml
- lib/validator/mod.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
1. If the periodic sync is disabled, skip syncing alltogether in `sync_to_tip`
2. Rework the full scan into using chain checkpoints. Do this only after the validator has finished its initial sync
> multi: rework sync for big wallets

- app/main.rs
- lib/bins.rs
- lib/wallet/mine.rs
1. Clearer error message and failure mode when unable to mine a new block
2. Refine panic hooks, to make it easier to pick up the actual message
3. Most important: let Bitcoin Core mine on its own when it's time for difficulty adjustments. I'm unable to get the PoW target calculations working correctly, and this is a hacky workaround that gets blocks flowing again.
> multi: mining fixes

- app/main.rs
Tolerate RPC errors from Bitcoin Core if they indicate Bitcoin Core being in warmup (-28).
> main: implement Bitcoin Core warmup wait

- lib/cli.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
This adds a new chain sync source that simply doesn't sync the wallet. When passing this there's no need to connect to an external chain source, which makes everything easier to wire up. Useful in integration test scenarios!
Note that the wallet is still updated on new block events received via Bitcoin Core.
> wallet: add no-sync source

- Cargo.lock
- Cargo.toml
- README.md
- app/Cargo.toml
- app/main.rs
- integration_tests/setup.rs
- integration_tests/util.rs
- lib/Cargo.toml
- lib/rpc_client.rs
- lib/validator/cusf_enforcer.rs
- lib/validator/dbs/block_hashes.rs
- lib/validator/main_rest_client.rs
- lib/validator/mod.rs
- lib/validator/task/error.rs
- lib/validator/task/mod.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/sync.rs
Notes: this relies on https://github.com/Ash-L2L/bip300301/pull/5 getting merged. 
Closes #195 
This is tested with a few different reorg scenarios on regtest. I've done tests with actual reorgs (two nodes running, where one overtakes the other), as well as by doing RPC calls to `invalidateblock`. Note that calling `invalidateblock` leads to a TODO panic within `cusf-enforcer-mempool`, but that is unrelated to this PR. 
The implementation here is rather chaotic and messy. I've tried my best to comment things liberally, but I'm very much open to suggestions on how to simplify. 
Stats for syncing headers on signet, on my Macbook Pro with Bitcoin Core running locally: 
* ~This PR: 5.05525225s~
* This PR after reorg logic integrated: 6.464624708s
* master: 47.817417791s
> validator: fetch block headers via REST

- Cargo.lock
- Cargo.toml
- app/main.rs
Currently the wallet assumes that the underlying node has `txindex` enabled. If this is not the case we'll fail later with cryptic error messages. Better to fail early!
It could very well be that the best choice here is to _remove_ the need for a TX index. That's a bigger task that can be done at a later point if needed.
Depends on https://github.com/LayerTwo-Labs/cusf-enforcer-mempool/pull/8.
Also, see https://github.com/LayerTwo-Labs/bip300301_enforcer/pull/205. To my knowledge it seems like the bip300301 dependency has to be bumped in tandem across two places. That's a bit frustrating. Any way around this? I tried modifying `Cargo.toml` with patch sections, but could not get it to work...
> main: verify txindex exists on wallet startup

- lib/server.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mod.rs
- lib/wallet/sync.rs
Closes #199 
Also handles chain splits. Note that there's no concept of "disconnecting a block" in BDK. Instead we're supposed to chug along with new block updates, and then BDK makes sure to keep track of all tips and automatically keep track of what's the best one.
> wallet: fix broken sync logic where multiple blocks are needed

- app/file_descriptors.rs
- app/main.rs
macOS has a pretty low standard limit for open file descriptors. If we get a task error that indicates that we've hit this limit, dump them into logs for debug purposes.
Note that this only works on macOS (due to `lsof`), therefore the `cfg!` guard.
> main: dump open files on task error indication

- .github/workflows/build_docker.yaml
- .github/workflows/check_lint_build_release.yaml
- Dockerfile
- rust-toolchain.toml
This allows us to centralize the Rust version number in a single place, and both CI and the Docker build can deduce their versions from this.
> dev: add rust-toolchain.toml file

- .github/workflows/check_lint_build_release.yaml
The Rust cache we tried to do prior to this commit did not work. Things were being built from scratch every time!
Instead, cache the binary itself. Also, pin the electrs version to a specific release.
> ci: change electrs caching

- lib/server.rs
- lib/wallet/mod.rs
Indicate with a bool whether the wallet has completed its first sync.
Closes #223
Matching PR for protos: https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/50
> wallet: make balance endpoint immediately available

- app/main.rs
- lib/wallet/cusf_block_producer.rs
- lib/wallet/error.rs
- lib/wallet/mod.rs
1. Instead of implicitly spawning a wallet sync task on wallet instantation, make this explicit and spawn from main.rs. This allows us to rip out some start/stop complexity, and also allows us to spawn the wallet sync task right away, instead of waiting until the validator has synced.
2. Remove callback usage from the mempool sync task. Instead return the synced mempool, and allow what used to be a callback instead be a regular function call on the mempool. Allows to reduce some complexity around senders/receivers.
3. Implement support for shutting down the `getblocktemplate` JSON-RPC server. Previously this was never cancelled, leading us to always hit the force shutdown after a short timeout.
4. Implement support for shutting down the main validator JSON-RPC server
This fixes the second …
> multi: refactor task structure, add shutdown to JSON-RPC server
